export const manager = [{
  'inputs': [{
    'internalType': 'address',
    'name': '_tyoeToken',
    'type': 'address',
  }, { 'internalType': 'address', 'name': '_usdtToken', 'type': 'address' }, {
    'internalType': 'address',
    'name': '_nftContract',
    'type': 'address',
  }, { 'internalType': 'address', 'name': '_usdtRecipient', 'type': 'address' }, {
    'internalType': 'address',
    'name': '_stakingRecipient',
    'type': 'address',
  }], 'stateMutability': 'nonpayable', 'type': 'constructor',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'nftCount',
    'type': 'uint256',
  }, { 'indexed': false, 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256' }, {
    'indexed': false,
    'internalType': 'uint256[]',
    'name': 'tokenIds',
    'type': 'uint256[]',
  }],
  'name': 'AirdropClaimed',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{
    'indexed': true,
    'internalType': 'address',
    'name': 'previousOwner',
    'type': 'address',
  }, { 'indexed': true, 'internalType': 'address', 'name': 'newOwner', 'type': 'address' }],
  'name': 'OwnershipTransferred',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': false, 'internalType': 'uint256', 'name': 'startTime', 'type': 'uint256' }],
  'name': 'ReleaseEnabled',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }],
  'name': 'RewardsClaimed',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }],
  'name': 'Staked',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'indexed': true,
    'internalType': 'uint256',
    'name': 'roundId',
    'type': 'uint256',
  }, { 'indexed': false, 'internalType': 'uint256', 'name': 'usdtAmount', 'type': 'uint256' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'tyoeAmount',
    'type': 'uint256',
  }],
  'name': 'SubscriptionPurchased',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'uint256', 'name': 'roundId', 'type': 'uint256' }],
  'name': 'SubscriptionRoundCompleted',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'uint256', 'name': 'roundId', 'type': 'uint256' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'usdtPrice',
    'type': 'uint256',
  }, { 'indexed': false, 'internalType': 'uint256', 'name': 'maxSlots', 'type': 'uint256' }],
  'name': 'SubscriptionRoundCreated',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }],
  'name': 'TokensReleased',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'indexed': false,
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }, { 'indexed': false, 'internalType': 'uint256', 'name': 'penalty', 'type': 'uint256' }],
  'name': 'Unstaked',
  'type': 'event',
}, {
  'inputs': [],
  'name': 'AIRDROP_AMOUNT',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'RELEASE_INTERVAL',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'RELEASE_PERCENTAGE',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'TOTAL_RELEASE_PERIODS',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'name': 'addressClaimed',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'roundId',
    'type': 'uint256',
  }],
  'name': 'calculateClaimableAmount',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'user', 'type': 'address' }],
  'name': 'calculateStakingRewards',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'claimAirdrop',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'claimStakingRewards',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'claimSubscriptionTokens',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': 'usdtPrice', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'maxSlots',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'immediateReleaseAmount', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'totalAmount',
    'type': 'uint256',
  }], 'name': 'createSubscriptionRound', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function',
}, {
  'inputs': [],
  'name': 'currentRoundId',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'dailyRewardRate',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': 'roundId', 'type': 'uint256' }],
  'name': 'deactivateSubscriptionRound',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'token', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }], 'name': 'emergencyWithdraw', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function',
}, {
  'inputs': [],
  'name': 'enableRelease',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'getCurrentActiveRound',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'user', 'type': 'address' }],
  'name': 'getStakingInfo',
  'outputs': [{ 'internalType': 'uint256', 'name': 'stakedAmount', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'pendingRewards',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'claimableRewards', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': 'roundId', 'type': 'uint256' }],
  'name': 'getSubscriptionRoundInfo',
  'outputs': [{ 'internalType': 'uint256', 'name': 'usdtPrice', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'maxSlots',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'currentSlots', 'type': 'uint256' }, {
    'internalType': 'bool',
    'name': 'active',
    'type': 'bool',
  }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'user', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'roundId',
    'type': 'uint256',
  }],
  'name': 'getUserSubscriptionInfo',
  'outputs': [{ 'internalType': 'uint256', 'name': 'totalAmount', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'releasedAmount',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'claimableAmount', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'name': 'nftClaimed',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'nftContract',
  'outputs': [{ 'internalType': 'contract IERC721Enumerable', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'owner',
  'outputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'releaseEnabled',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'releaseStartTime',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'renounceOwnership',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': '_rate', 'type': 'uint256' }],
  'name': 'setDailyRewardRate',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': '_penalty', 'type': 'uint256' }],
  'name': 'setStakingPenalty',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '_stakingRecipient', 'type': 'address' }],
  'name': 'setStakingRecipient',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '_tyoeToken', 'type': 'address' }],
  'name': 'setTYOE',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '_usdtRecipient', 'type': 'address' }],
  'name': 'setUsdtRecipient',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '_usdtToken', 'type': 'address' }],
  'name': 'setUsdtToken',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256' }],
  'name': 'stake',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'name': 'stakingInfo',
  'outputs': [{ 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'startTime',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'lastRewardTime', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'pendingRewards',
    'type': 'uint256',
  }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'stakingPenalty',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'stakingRecipient',
  'outputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'subscribe',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'name': 'subscriptionRounds',
  'outputs': [{ 'internalType': 'uint256', 'name': 'usdtPrice', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'maxSlots',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'currentSlots', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'immediateReleaseAmount',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'totalAmount', 'type': 'uint256' }, {
    'internalType': 'bool',
    'name': 'active',
    'type': 'bool',
  }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'totalStaked',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'newOwner', 'type': 'address' }],
  'name': 'transferOwnership',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'tyoeToken',
  'outputs': [{ 'internalType': 'contract IERC20', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'unstake',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': 'roundId', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'newUsdtPrice',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'newMaxSlots', 'type': 'uint256' }],
  'name': 'updateSubscriptionRound',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'usdtRecipient',
  'outputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'usdtToken',
  'outputs': [{ 'internalType': 'contract IERC20', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': '',
    'type': 'uint256',
  }],
  'name': 'userSubscriptions',
  'outputs': [{ 'internalType': 'uint256', 'name': 'totalAmount', 'type': 'uint256' }, {
    'internalType': 'uint256',
    'name': 'releasedAmount',
    'type': 'uint256',
  }, { 'internalType': 'uint256', 'name': 'lastReleaseTime', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'name': 'userTotalSubscriptions',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}];

export const token = [{ 'inputs': [], 'stateMutability': 'nonpayable', 'type': 'constructor' }, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'owner', 'type': 'address' }, {
    'indexed': true,
    'internalType': 'address',
    'name': 'spender',
    'type': 'address',
  }, { 'indexed': false, 'internalType': 'uint256', 'name': 'value', 'type': 'uint256' }],
  'name': 'Approval',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{
    'indexed': true,
    'internalType': 'address',
    'name': 'previousOwner',
    'type': 'address',
  }, { 'indexed': true, 'internalType': 'address', 'name': 'newOwner', 'type': 'address' }],
  'name': 'OwnershipTransferred',
  'type': 'event',
}, {
  'anonymous': false,
  'inputs': [{ 'indexed': true, 'internalType': 'address', 'name': 'from', 'type': 'address' }, {
    'indexed': true,
    'internalType': 'address',
    'name': 'to',
    'type': 'address',
  }, { 'indexed': false, 'internalType': 'uint256', 'name': 'value', 'type': 'uint256' }],
  'name': 'Transfer',
  'type': 'event',
}, {
  'inputs': [],
  'name': 'TOTAL_SUPPLY',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'owner', 'type': 'address' }, {
    'internalType': 'address',
    'name': 'spender',
    'type': 'address',
  }],
  'name': 'allowance',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'spender', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }],
  'name': 'approve',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'account', 'type': 'address' }],
  'name': 'balanceOf',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256' }],
  'name': 'burn',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'decimals',
  'outputs': [{ 'internalType': 'uint8', 'name': '', 'type': 'uint8' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'spender', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'subtractedValue',
    'type': 'uint256',
  }],
  'name': 'decreaseAllowance',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'spender', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'addedValue',
    'type': 'uint256',
  }],
  'name': 'increaseAllowance',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'to', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }], 'name': 'mint', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function',
}, {
  'inputs': [],
  'name': 'name',
  'outputs': [{ 'internalType': 'string', 'name': '', 'type': 'string' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'owner',
  'outputs': [{ 'internalType': 'address', 'name': '', 'type': 'address' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'renounceOwnership',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'symbol',
  'outputs': [{ 'internalType': 'string', 'name': '', 'type': 'string' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [],
  'name': 'totalSupply',
  'outputs': [{ 'internalType': 'uint256', 'name': '', 'type': 'uint256' }],
  'stateMutability': 'view',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'to', 'type': 'address' }, {
    'internalType': 'uint256',
    'name': 'amount',
    'type': 'uint256',
  }],
  'name': 'transfer',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'from', 'type': 'address' }, {
    'internalType': 'address',
    'name': 'to',
    'type': 'address',
  }, { 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256' }],
  'name': 'transferFrom',
  'outputs': [{ 'internalType': 'bool', 'name': '', 'type': 'bool' }],
  'stateMutability': 'nonpayable',
  'type': 'function',
}, {
  'inputs': [{ 'internalType': 'address', 'name': 'newOwner', 'type': 'address' }],
  'name': 'transferOwnership',
  'outputs': [],
  'stateMutability': 'nonpayable',
  'type': 'function',
}];